name: "Open WebUI"
description: "Open WebUI is an extensible, self-hosted interface for AI that adapts to your workflow, all while operating entirely offline."
# renovate: datasource=github-releases depName=open-webui/open-webui
version: "v0.5.18"
slug: "open-webui"
arch:
  - aarch64
  - amd64
url: https://openwebui.com
environment:
#  OPENAI_API_KEY: "$(bashio::config 'openai_api_key')"
  ENABLE_OLLAMA_API: "False"
map:
  - type: addon_config
    read_only: False
    path: /app/backend/data
legacy: True
host_network: True
options:
  openai_api_key: "OpenAI Key"
schema:
  message: "str?"
image: ghcr.io/open-webui/open-webui
init: false
ingress: true
ingress_port: 8080
ingress_stream: true
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: "Open WebUI"
startup: application
watchdog: tcp://[HOST]:[PORT:8080]
