name: "Open WebUI"
description: "Open WebUI is an extensible, self-hosted interface for AI that adapts to your workflow, all while operating entirely offline."
version: "v0.3.32"
slug: "open-webui"
arch:
  - aarch64
  - amd64
url: https://openwebui.com
map:
  - type: addon_config
    read_only: False
    path: /app/backend/data

options:
  env_vars: []
image: ghcr.io/open-webui/open-webui
init: false
ingress: true
ingress_port: 8080
ingress_stream: true
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: "Open WebUI"
startup: application
watchdog: tcp://[HOST]:[PORT:8080]

schema:
  env_vars:
    - name: match(^GF_([A-Z0-9_])+$)
      value: str