name: "Open WebUI"
description: "Open WebUI is an extensible, self-hosted interface for AI that adapts to your workflow, all while operating entirely offline."
# renovate: datasource=github-releases depName=open-webui/open-webui
version: "0.5.18-1"
slug: "open-webui"
arch:
  - aarch64
  - amd64
url: https://openwebui.com
environment:
#  OPENAI_API_KEY: "$(bashio::config 'openai_api_key')"
  ENABLE_OLLAMA_API: "False"
  PORT: "$(bashio::config 'port')"
map:
  - type: addon_config
    read_only: False
    path: /app/backend/data
legacy: True
host_network: True
options:
  openai_api_key: "OpenAI Key"
  port: 8080
schema:
  message: "str?"
  openai_api_key: "str"
  port: "port"
image: "ghcr.io/open-webui/open-webui:v0.5.18"
init: false
ingress: true
ingress_port: "$(bashio::config 'port')"
ingress_stream: true
ports:
  8080/tcp: "$(bashio::config 'port')"
ports_description:
  8080/tcp: "Open WebUI"
startup: application
watchdog: tcp://[HOST]:[PORT:$(bashio::config 'port')]
